name: Chromatic Deployment

on:
  pull_request:
    paths:
      - 'pkg/interface/**'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    name: "Deploy Chromatic"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: cd 'pkg/interface' && npm i
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          working-directory: pkg/interface
